#!/usr/bin/env python3
"""Collect the F3's hal_parse("...") start-up lines from stm32f303/src/main.c.

The harness runs the same load/link sequence as the board, taken from the
firmware source each build, so it cannot drift from it.

usage: extract_init.py out.c stm32f303/src/main.c
"""
import re
import sys

lines = []
with open(sys.argv[2]) as f:
    for line in f:
        code = line.split('//')[0]
        m = re.search(r'^\s*hal_parse\("((?:[^"\\]|\\.)*)"\);', code)
        if m:
            lines.append(m.group(1))
if not lines:
    sys.exit('extract_init: no hal_parse lines in ' + sys.argv[2])

with open(sys.argv[1], 'w') as f:
    f.write('// generated by tests/sim/tools/extract_init.py from %s, DO NOT EDIT\n' % sys.argv[2])
    f.write('const char *const f3_init_lines[] = {\n')
    for l in lines:
        f.write('    "%s",\n' % l)
    f.write('    0,\n};\n')
