#!/usr/bin/env python3
"""Write a no-op HAL component with the same name and pins as a firmware one.

The host harness has no hardware behind encf, sserial, adc, io4 and the other
src/comps drivers. A shell keeps their pins, so the conf templates load and
link unchanged; the runner writes the outputs it models (encf0.pos,
sserial0.pos_cmd, ...) directly, and everything else stays at 0.

usage: gen_shell.py out.c in.c
"""
import os
import re
import sys

out, src = sys.argv[1], sys.argv[2]
comp = None
pins = []
with open(src) as f:
    for line in f:
        m = re.search(r'HAL_COMP\((\w*)\);', line)
        if m:
            comp = m.group(1)
        m = re.search(r'HAL_PIN\((\w*)\)', line)
        if m:
            pins.append('HAL_PIN(%s);' % m.group(1))
        m = re.search(r'HAL_PINA\((\w*),\s*(\d*)\)', line)
        if m:
            pins.append('HAL_PINA(%s, %s);' % (m.group(1), m.group(2)))
if not comp:
    sys.exit('gen_shell: no HAL_COMP in ' + src)

with open(out, 'w') as f:
    f.write('// generated by tests/sim/tools/gen_shell.py from %s, DO NOT EDIT\n' % src)
    f.write('#include "%s_comp.h"\n#include "hal.h"\n\n' % os.path.splitext(os.path.basename(src))[0])
    f.write('HAL_COMP(%s);\n\n' % comp)
    f.write('\n'.join(pins) + '\n\n')
    f.write('hal_comp_t %s_comp_struct = {\n' % comp)
    f.write('    .name      = "%s",\n' % comp)
    f.write('    .ctx_size  = 0,\n')
    f.write('    .pin_count = sizeof(struct %s_pin_ctx_t) / sizeof(struct hal_pin_inst_t),\n};\n' % comp)
